project:
  type: book
book:
  title: "Production of seasonally adjusted series"
  subtitle: "JDemetra+ and R Cookbook"

  reader-mode: false
  sharing: [facebook, twitter, linkedin]

  page-footer:
    right: |
      <li><a href="https://github.com/annasmyk/Prod-SA-JDemetra-Cookbook" target="blank">Code source</a></li>
    left: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  repo-actions: [edit,issue]
  site-url: https://jdemetra-new-documentation.netlify.app/
  repo-url: https://github.com/annasmyk/Prod-SA-JDemetra-Cookbook
  repo-branch: main
  # cover-image: resources/logo-utilitr.png
  # favicon: resources/logo-utilitr.png

  sidebar:
    style: "floating"
    search: true
    collapse-level: 1

  author:
    - name: Anna Smyk
      url: https://github.com/annasmyk
      affiliations:
        - name: Insee
          country: France
          city: Paris
          url: "https://www.insee.fr/fr/accueil"
    - name: Tanguy Barthelemy
      url: https://github.com/TanguyBarthelemy
      affiliations:
        - name: Insee
          country: France
          city: Paris
          url: "https://www.insee.fr/fr/accueil"
      role: "Author"

  date: "02/28/2026"
  page-navigation: true
  chapters:
    - index.qmd
    - introduction.qmd
    - P1-Overview.qmd
    # - P2-Build.qmd
    # - P3-Review.qmd
    # - P4-Appendices.qmd
    - references.bib
bibliography: references.bib
format:
  html:
    grid:
      body-width: 800px
    theme:
        - united
        - custom.scss
    css: styles.css
  pdf:
    mainfont: "DejaVu Sans"
    documentclass: scrreprt

editor: source
